dist: xenial

git:
  depth: false

language: python

cache: pip

python:
  - 3.6
  - 3.7
  - 3.8

install:
  - pip install -r browser/requirements.txt
  - pip install -r browser/requirements-test.txt

script:
  - pytest browser --cov browser --pep8

after_success:
  - coveralls
