branch-defaults:
  add-c-to-cells:
    environment: deepcell-label-dev
  caliban-visualizer:
    environment: tracks-visualizer
  convert-divisions:
    environment: deepcell-label-dev
  deployment-guide:
    environment: deepcell-label-dev
  dev-documentation:
    environment: label-stable
  export-zip:
    environment: deepcell-label-dev
  fix-mesmer-loading:
    environment: label-stable
  fix-predict-loading:
    environment: label-stable
  force-load-output:
    environment: deepcell-label-dev
  main:
    environment: label-stable
  react-prototype:
    environment: predict-visualizer
  spots-visualizer:
    environment: spots-visualizer
  tracking-ui:
    environment: tracking-test
  update-instructions:
    environment: deepcell-label-dev
environment-defaults:
  label-stable:
    branch: null
    repository: null
global:
  application_name: caliban-test-with-db
  default_ec2_keyname: null
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
